#!/bin/bash

# Check if the user running the script is root or using sudo
if [ "$(id -u)" -ne 0 ]; then
  echo "Please run this script as root or using sudo."
  exit 1
fi

# Download the OpenJDK package
wget https://download.oracle.com/java/20/latest/jdk-20_linux-x64_bin.deb

# Install the downloaded package
sudo apt-get -qqy install ./jdk-20_linux-x64_bin.deb

# Update the Java alternatives
sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-20/bin/java 1919

# Clean up by removing the downloaded package
rm ./jdk-20_linux-x64_bin.deb

echo "OpenJDK's installation completed successfully."

