#!/bin/bash

# Configuration file to store the Git repository
config_file="$HOME/update_app_config.txt"

# Your Github username and access token
# Note: Consider moving these to a more secure location
username="YOUR_USERNAME"
access_token="YOUR_ACCESS_TOKEN"

# Read the saved configuration if it exists
if [ -f "$config_file" ]; then
  gitrepo=$(cat "$config_file")
fi

# Check if the required arguments are provided, or if they are not saved yet
if [ $# -ne 1 ] && [ -z "$gitrepo" ]; then
  echo "Usage: $0 <gitrepo>"
  exit 1
fi

# Save the arguments if they are provided
if [ $# -eq 1 ]; then
  gitrepo=$1
  echo "$gitrepo" > "$config_file"
fi

# Append the username and access token to the Git repository URL
gitrepo="https://${username}:${access_token}@${gitrepo#https://}"

pidfile="nohup-java-pid.txt"

# Kill the previously running Java process with nohup, if any
if [ -f "$pidfile" ]; then
    old_pid=$(cat "$pidfile")
    if ps -p $old_pid > /dev/null; then
        kill -9 $old_pid
    fi
    rm "$pidfile"
fi

# Get the repository name from the gitrepo URL
directory=$(basename "$gitrepo" .git)

# Remove the specified directory
if [ -d "$directory" ]; then
  echo "Removing $directory..."
  rm -rf "$directory"
else
  echo "Directory $directory not found. Skipping removal."
fi

# Clone the specified Git repository
echo "Cloning $gitrepo..."
git clone "$gitrepo" || { echo "Error: Failed to clone $gitrepo"; exit 1; }

# Change to the cloned repository directory
cd "$directory" || { echo "Error: Failed to enter repository directory"; exit 1; }

# Build the Maven project (package)
echo "Building Maven project..."
bash ./mvnw package || { echo "Error: Maven build failed"; exit 1; }

# Find the generated JAR file
jarfile=$(find target -iname '*SNAPSHOT.jar' | head -n 1)
if [ -z "$jarfile" ]; then
  echo "Error: JAR file not found"
  exit 1
fi

# Run the Java JAR file with nohup
echo "Running Java JAR file with nohup..."
nohup java -jar "$jarfile" &>/dev/null &

# Save the process ID
echo $! > "$pidfile"

echo "Java application has been updated and is running with PID $!"
